name: hello
on: 
#  push: 
#    branches:
    

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: say hello
        run: echo "Hello user"

      - name: Print
        run: date 

      - name: print branch name
        run: |
          echo "Branch: ${{ github.ref_name }}"

      - name: print list of all files
        run: ls -la

      - name: Print runner name
        run: |
          echo "OS: $RUNNER_OS"

