name: manual
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment (staging/production)"
        type: choice
        required: true
        options:
          - staging
          - prod
        

jobs:
  manual:
    runs-on: ubuntu-slim
    steps:
      - name: Print selected environment
        run: |
          echo "Environment: ${{ inputs.environment }}"
      
