name: manual
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment (staging/production)"
        type: environment
        required: true
        default: "staging"

jobs:
  manual:
    runs-on: ubuntu-slim
    steps:
      - name: Print selected environment
        run: |
          echo "Environment: ${{ inputs.environment }}"
      
