name: output
on:
  workflow_dispatch:

jobs:
  set-output:
    runs-on: ubuntu-latest
    steps:
      - name: sets an output
        run: echo "date=$(date)" >> $GITHUB_OUTPUT
  read-output:
    runs-on: ubuntu-latest
    needs: set-output
    steps:
      - name: read an output from previous step
        run: | 
          echo "Output: ${{ needs.set-output.outputs.date }}
      
