name: check
on:
  pull_request:
    branches: 
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: print the branch name
        run: |
          echo "PR check running for branch: ${{ github.ref_name }}"

    
