name: check
#on:
#  pull_request:
#    branches: 
#      - main
#      - test
#on:
#   schedule:
#     - cron: "0 9 * * 1"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: print the branch name
        run: |
          echo "PR check running for branch: ${{ github.ref_name }}"

    
